# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: Swift Management CI

on:
  push:
    branches: [ master, develop, app ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x  
    - name: Install Dependencies
      run: npm --prefix ./swift-management-app install
    - name: Build
      run: npm --prefix ./swift-management-app run build
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Download Production Artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:lumiqon-swift-management
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Cleanup Production Artifact
      uses: geekyeggo/delete-artifact@v1
      with:
        name: dist
        failOnError: false
