# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: Swift Management CI

on:
  push:
    branches: [ master, develop, app ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x  
    - name: Install Dependencies
      run: npm --prefix ./swift-management-app ci
    - name: Build
      run: npm --prefix ./swift-management-app run build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:lumiqon-swift-management
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        PROJECT_PATH: ./swift-management-app
